workflows:
  android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      java: 11
      node: 18
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
    scripts:
      - name: Install npm dependencies
        script: |
          npm ci
      - name: Build React app
        script: |
          npm run build
      - name: Set up Android environment
        script: |
          echo "sdk.dir=$ANDROID_SDK_ROOT" > "$CM_BUILD_DIR/android/local.properties"
          ls -la android/
      - name: Build Android APK
        script: |
          cd android
          chmod +x gradlew
          ls -la
          ./gradlew clean assembleDebug --info
    artifacts:
      - android/app/build/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - info@timgrow.com
        notify:
          success: true
          failure: false
